### ISSUE TITLE
No u2fval.conf available

### ISSUE THREAD

**Issue by leihw** [Yubico/u2fval#1]
I downloaded and tried to install it to my centos botx, but I got the error. Where can I get this conf file?
error: can't copy 'conf/u2fval.conf': doesn't exist or not a regular file

**Comment by dainnilsson** [comment]
When installing from Git you will need to build a source tarball first:

$ python setup.py sdist

This creates the tarball in the dist/ directory, which can then be installed as usual (using pip for example).

The /conf/u2fval.conf file is a copy of u2fval/default_settings.py
