### ISSUE TITLE
u2fv client create -h

### ISSUE THREAD

**Issue by patatetom** [Yubico/u2fval#10]
the command line help for client create returns :
```
$ u2fval client create -h
usage: u2fval client create [-h] -a APPID -f FACET [FACET ...] <name>

positional arguments:
  <name>                the name of the client

optional arguments:
  -h, --help            show this help message and exit
  -a APPID, --appId APPID
                        sets the appId
  -f FACET [FACET ...], --facets FACET [FACET ...]
                        all valid facets for the client
```
with client name as last argument.
when used in this way, u2fval returns an error :
```
$ u2fval client create -a https://localhost -f https://localhost mywebapp
usage: u2fval client create [-h] -a APPID -f FACET [FACET ...] <name>
u2fval client create: error: too few arguments
```
this error doesn't occur when client name is the first argument :
```
$ u2fval client create mywebapp -a https://localhost -f https://localhost
Created client: mywebapp
```

**Comment by dainnilsson** [comment]
I suspect the reason for this is that -f takes multiple arguments, and it's treating "mywebapp" as an additional facet. I'm not sure if we should try to fix this so that it correctly understands that "mywebapp" is the name, or just change the --help output.

**Comment by patatetom** [comment]
you are right, "mywebapp" is undoubtedly considered as an additional facet and as the client name.

**Comment by patatetom** [comment]
action='append' can be used in -f/--facet argument :
```python
    create_parser.add_argument('-f', '--facet', required=True, action='append',
                               metavar='FACET', dest='facets',
                               help='valid facet for the client (can be repeated several times)')
```

but the help message delivered is not explicit :
```
$ u2fval client create -h
usage: u2fval client create [-h] -a APPID -f FACET <name>

positional arguments:
  <name>                the name of the client

positional arguments:
  <name>                the name of the client

optional arguments:
  -h, --help            show this help message and exit
  -a APPID, --appId APPID
                        sets the appId
  -f FACET, --facet FACET
                        valid facet for the client (can be repeated several
                        times)
```

the right usage message should be something like this :
```
$ u2fval client create -h
usage: u2fval client create [-h] -a APPID -f FACET [-f FACET [-f FACET [ ... ]]] <name>
...
```

*however, it looks like a bug in the python argparse module...*

lacsaP

**Comment by dainnilsson** [comment]
I'm committed a workaround in 0bd7a1f. It's not perfect, but it seems to do the job. Basically I made *name* optional, with a custom action that takes the last value of *--facets* if more than one are given. The downside is that the *--help* output shows *name* as optional, by placing square brackets around it.
