### ISSUE TITLE
sample config file

### ISSUE THREAD

**Issue by osallou** [Yubico/u2fval#15]
Doc states:
"Configuration is kept in /etc/yubico/u2fval/u2fval.conf, see the default configuration file for more information (also available in the conf/ directory of any source release of this project)."

But when installed via pip, there is no conf file created. In github source, under conf directory, so is no conf file either. Could you provider an example we could use?

**Comment by dainnilsson** [comment]
It's only installed if you have permissions to write to the /etc/yubico/u2fval directory. The source tar.gz should contain the file (which you can get from here: https://github.com/Yubico/u2fval/releases/download/u2fval-0.9.1/u2fval-0.9.1.tar.gz)
It's just a copy of this file: https://github.com/Yubico/u2fval/blob/master/u2fval/default_settings.py
