### ISSUE TITLE
ImportError: No module named 'u2fval.yubicommon'

### ISSUE THREAD

**Issue by vsvankhede** [Yubico/u2fval#21]
While creating source distribution, I'm getting following  error:

```
Traceback (most recent call last):
    File "setup.py", line 29, in (module)
       from u2fval.yubicommon.setup import setup
ImportError: No module named 'u2fval.yubicommon'
```

**Comment by a-dma** [comment]
have you run ``git submodule init`` and ``git submodule update`` ?

**Comment by vsvankhede** [comment]
Yes, I had run both commands. I'm following the instructions given [here](https://developers.yubico.com/u2fval/).

**Comment by dainnilsson** [comment]
What OS are you running? Is there anything in vendor/yubicommon?

**Comment by vsvankhede** [comment]
Windows. Yes there is some src files into vendor/yubicommon. I'm new to python so, may be I missing something to configure path environment variable specific to python project.

**Comment by dainnilsson** [comment]
Ah, that explains it. Windows doesn't support symlinks which is causing
this issue. This should be better documented. Inside u2fval/ there is a
yubicommon symlink which on Windows shows up as a file. You'll need to
delete that file and replace it with a copy of the directory
vendor/yubicommon/yubicommon. In the end you should have
u2fval/yubicommon/__init__.py, etc. After that you should be able to build
the source release.
