### ISSUE TITLE
fatal error: ffi.h: No such file or directory

### ISSUE THREAD

**Issue by matleses** [Yubico/u2fval#22]
Samething with pip and git 

`Processing cffi-1.7.0.tar.gz
Writing /tmp/easy_install-nmmcB2/cryptography-1.4/temp/easy_install-KHtVMD/cffi-1.7.0/setup.cfg
Running cffi-1.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nmmcB2/cryptography-1.4/temp/easy_install-KHtVMD/cffi-1.7.0/egg-dist-tmp-5eKERO
compiling '_configtest.c':
__thread int some_threadlocal_variable_42;

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by dainnilsson** [comment]
Looks like a missing build dependency for cryptography, see their installation instructions at cryptography.io
