### ISSUE TITLE
u2fval does not work with uwsgi

### ISSUE THREAD

**Issue by tanji** [Yubico/u2fval#26]
It seems that u2fval does not work anymore with uwsgi. When I switch my installation from standalone server to uwsgi (keeping the same config and DB), the API replies:

```curl http://localhost:80/client
{"errorMessage": "Client not specified", "errorCode": 10}
```

**Comment by tanji** [comment]
OK, so this is in the code comments, but not in the documentation:

**Comment by dainnilsson** [comment]
This information is in the README, and a more detailed example on the Apache_Deployment page.
