### ISSUE TITLE
Yubikey 4 device metadata not being saved or accessible

### ISSUE THREAD

**Issue by MRuth** [Yubico/u2fval#28]
When using version 1.0.1 of the Yubico u2fval server, I am able to access the device metadata for the Yubico Yubikey NEO and the FIDO security Key, but the u2fval server does not seem to be fetching the proper device metadata for the Yubikey 4 series.

Here is the JSON response from the u2fval server when retrieving all registered Yubikeys (Yubikey NEO, Yubikey Security Key, and Yubikey 4).
[RegisteredYubikeys.txt](https://github.com/Yubico/u2fval/files/836886/RegisteredYubikeys.txt)

**Comment by dainnilsson** [comment]
There's a json file containing the metadata located in /etc/yubico/u2fval/metadata/. Unfortunately the version of this file that is bundled with u2fval is out of date, and does not contain the YubiKey 4 entry. If you replace the file with this current one: https://developers.yubico.com/U2F/yubico-metadata.json that should take care of it.

**Comment by dainnilsson** [comment]
New version out, with updated metadata.
