### ISSUE TITLE
u2fval SQL issue when removing and re-adding keys for MySQL connector 

### ISSUE THREAD

**Issue by MRuth** [Yubico/u2fval#29]
When using the SQLAlchemy MYSQL connector, I am able to successfully initialize the database, register clients, register new devices for user accounts, and authenticate against those devices.

However, when the u2fval server seems to try to delete a registered device, the entry in the certificates table does not get removed by the deletion process.  Upon re-registering the same device, the sql queries fail due to a duplicate key found within the certificates table.

Here is the error message returned while trying to POST a registration event for a device that had been successfully registered and then deleted back to the u2fval server.

<html>
    <head>
        <title>500 Internal Server Error</title>
    </head>
    <body>
        <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.
        <br />
        <br />
(_mysql_exceptions.IntegrityError) (1062, &quot;Duplicate entry 'f6d641a7dcb479c748ecb4a259358699' for key 'fingerprint'&quot;)
    </body>
</html>

**Comment by MRuth** [comment]
So with a little more digging, it seems that a SHA1 hash is being calculated on the device fingerprint and then turned into a hex string to be stored and queried later.  SHA1 creates a 160 bit message digest which is turned into a 40 character hex string.

For some RDBMS implementations, such as MySQL, string columns are capped at the maximum length specified when creating the table.  When the certificates table is created, the fingerprint column is only allocated 32 characters when it should have 40 allocated.

As a side question, aren't SHA1 hashes considered insecure now?  Would it be beneficial to move to SHA256 or higher?

[Link to line number of issue, should be changed to String(40)](https://github.com/Yubico/u2fval/blob/master/u2fval/model.py#L115)

**Comment by dainnilsson** [comment]
Thanks for reporting this, the column length is indeed incorrect as you've found. Different DBs handle this issue differently, but it looks like the alternatives are that it ignores the length (sqlite), truncates the value (mysql) or rejects the insert (postgres). These different cases make migrating a bit difficult. I'm leaning towards changing the algorithm to take a SHA256 fingerprint of the cert, base64 encode it and truncate it to 32 characters (giving us 24 bytes of the hash, which is sufficient). This means all fingerprints will need to be re-calculated, but that is easy to script. It also means that we don't have to modify the table structure, which is nice. Any thoughts on that approach?

**Comment by MRuth** [comment]
That would be the best option if table structure stability is required..I don't have any idea on where this code implementation is being used (in high-stakes production vs testing or small projects).  If table structure modification is possible and not too destructive, I would think just a hex encoded SHA256 bit hash would be the most secure.

**Comment by dainnilsson** [comment]
Upon further consideration, I've decided to go ahead and change the column length. Not having to truncate the fingerprint and leaving it in hex seems cleaner and is easier to read, so I'm going to opt for that over keeping the database structure intact. Security-wise it shouldn't make a difference.

**Comment by MRuth** [comment]
That sounds good.  While I haven't noticed any other issues with database migrations, it may be easier now to try and see if any other columns have similar issues and take care of them at the same time.  If there is anything I can do to help with this, let me know.

**Comment by dainnilsson** [comment]
I've gone over the columns and resized some of them. Nothing has issues like this, but some of the columns were made slightly bigger just to make things more consistent. If you'd like to test it out the changes are available in the `v2` branch, which I'll probably merge into master and release during next week. Note that there are a bunch of other backward incompatible changes, notably in the API, so upgrading might not be trivial.

**Comment by dainnilsson** [comment]
Marking this as Closed, now that 2.0 is out.
