### ISSUE TITLE
Not finding 'clients' table

### ISSUE THREAD

**Issue by FreeMyEHR** [Yubico/u2fval#32]
Hi I'm trying to setup on Windows Server 2012 with python 3.6 installed. I am able to run the command:
`u2fval --config u2fval.conf db init`
which returns `Database initialized!` on a MySQL database. In the database I can see that tables **certificates, clients, devices, properties, transactions, users** are created.
However when I run the command:
`u2fval client create test https://test.com`
I get the following error after a long list of errors with line numbers:
`  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\sqlalchem
y\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: clients [SQL: 'INSERT INT
O clients (name, app_id, valid_facets) VALUES (?, ?, ?)'] [parameters: ('test', 'https://test.com', '["https://test.com"]')]`

My initial thought was that sqlite3 is being used to connect, but that doesn't make sense because the `db init` command works. I have gotten the same error when trying to connect to a sqlite database.

**Comment by dainnilsson** [comment]
Hi, it looks like you're not passing the `--config` parameter when invoking the `client create` command, which would explain the error you're getting. You'll have to pass this to each command you run, or set the environment variable U2FVAL_SETTINGS to point to the location of the file.
