### ISSUE TITLE
Chrome 66.X not works ):

### ISSUE THREAD

**Issue by chelo556** [Yubico/u2fval#36]
Hello 

We have a implementation using u2f_val, Chrome (on Windows 10) and Yubikey security key (a blue one), It works well until Google's Chrome 65.XXX, but someday Google's Chrome 66.XXX comes and everything is wrong ):

U2F_VAL can't register a new user, but It can authenticate 

Do you know what's the issue?

with Google´s Chrome 66.XXX the Yubico's demo page works   ):

We use 7000 yubikeys, so... It's a PROBLEM ):

**Comment by dainnilsson** [comment]
Chrome 66 made some changes in regards to registration, see my response in #38 fro details, and a workaround.
