### ISSUE TITLE
u2fval.conf file missing from PIP install

### ISSUE THREAD

**Issue by Xanir** [Yubico/u2fval#40]
No default u2fval.conf config file exists in a PIP install.
No default values exist for u2fval when installing form pip so the tables are not created. I am only running this to test the service and an in memory DB is perfectly acceptable  however I get the following then running `u2fval client list`

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: clients

which appears to be related to the lack of a config file. Also digging into the installed location of the package form pip I am not finding a conf folder or a u2fval.conf file

**Comment by dainnilsson** [comment]
pip is only able to create the settings file if it has permissions to do so (which typically requires root). The default file is available in the conf/ directory of the source release .tar.gz (you can find one on the releases page of this repository), or alternatively you can just look here: https://github.com/Yubico/u2fval/blob/master/u2fval/default_settings.py

**Comment by Xanir** [comment]
pip is being run as root, as this is being done inside a Dockerfile.
So are you saying I need the .tar.gz should not be using `pip install u2fval`?

From `pip show u2fval` I get the following
Name: u2fval
Version: 2.0.0
Summary: Standalone/WSGI U2F server implementing the U2FVAL protocol
Home-page: https://github.com/Yubico/u2fval
Author: Dain Nilsson
Author-email: dain@yubico.com
License: BSD 2 clause
Location: /usr/local/lib/python3.7/site-packages
Requires: python-u2flib-server, flask, flask-sqlalchemy
Required-by: 

This is the contents of /usr/local/lib/python3.7/site-packages/u2fval

- __init__.py
- __pycache__
- cli.py
- core
- core/__init__.py
- core/__pycache__
- default_settings.py
- exc.py
- jsobjects.py
- model.py
- transactiondb.py
- view.py

There is no /conf folder or a .conf file anywhere.


To your point of looking at default_settings.py, is that actually the .conf file even though it has a .py exception? If the blank path valid for SQLALCHEMY_DATABASE_URI the default in memory SQL DB?

**Comment by Xanir** [comment]
Or are you saying the pip does not setup the config file and that I need manually extract this file?
If so what I am to do with this file, I am not seeing any documentation about the file other than the default expected location of /etc/yubico/u2fval/u2fval.conf

**Comment by dainnilsson** [comment]
Yes, the default_settings.py can simply be renamed and placed in the proper location (/etc/yubico/u2fval/u2fval.conf). The comments in that file should explain the various options.
You won't be able to use an in-memory database with the command line tool, as the database exists only for the duration of the process, so the call to `u2fval db init` will initialize an in-memory database, but that database will immediately be destroyed as the process ends, and your call to `u2fval client list` will use a new empty database each time.
