### ISSUE TITLE
Database initialization raise an ImportError

### ISSUE THREAD

**Issue by patatetom** [Yubico/u2fval#8]
hi,
the `u2fval db init` raise an ImportError : 
```
# source u2fval.without.wheel/bin/activate

(u2fval.without.wheel) # pip list
cachetools (1.1.1)
M2Crypto (0.22.3)
pip (7.1.2)
pyasn1 (0.1.8)
pyasn1-modules (0.0.7)
python-u2flib-server (3.2.0)
setuptools (18.2)
SQLAlchemy (1.0.8)
u2fval (0.9.0)
WebOb (1.4.1)

(u2fval.without.wheel) # u2fval db init
Traceback (most recent call last):
  File "/root/u2fval.without.wheel/bin/u2fval", line 9, in <module>
    load_entry_point('u2fval==0.9.0', 'console_scripts', 'u2fval')()
  File "/root/u2fval.without.wheel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/u2fval.without.wheel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/root/u2fval.without.wheel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/root/u2fval.without.wheel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named main

(u2fval.without.wheel) # deactivate 
```

**Comment by patatetom** [comment]
hi,
may be this will do the trick...

```diff
--- u2fval.egg-info/entry_points.txt.bak	2015-09-14 22:39:06.967079634 +0200
+++ u2fval.egg-info/entry_points.txt	2015-09-14 22:39:19.313746836 +0200
@@ -1,3 +1,3 @@
 [console_scripts]
-u2fval = u2fval.cli.main
+u2fval = u2fval.cli
```

**Comment by patatetom** [comment]
$ virtualenv2 u2fval.with.wheel
New python executable in u2fval.with.wheel/bin/python2
Also creating executable in u2fval.with.wheel/bin/python
Installing setuptools, pip, wheel...done.

$ source u2fval.with.wheel/bin/activate

(u2fval.with.wheel) $ pip list
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)

(u2fval.with.wheel) $ pip install /tmp/u2fval-0.9.0.entry.point.changed.tar.gz 
Processing ./u2fval-0.9.0.entry.point.changed.tar.gz
Collecting python-u2flib-server>=3.1 (from u2fval==0.9.0)
Collecting SQLAlchemy (from u2fval==0.9.0)
Collecting WebOb (from u2fval==0.9.0)
Collecting cachetools (from u2fval==0.9.0)
  Using cached cachetools-1.1.1-py2.py3-none-any.whl
Collecting M2Crypto (from python-u2flib-server>=3.1->u2fval==0.9.0)
Collecting pyasn1>=0.1.7 (from python-u2flib-server>=3.1->u2fval==0.9.0)
Collecting pyasn1-modules (from python-u2flib-server>=3.1->u2fval==0.9.0)
Building wheels for collected packages: u2fval
  Running setup.py bdist_wheel for u2fval
  Stored in directory: /home/pascal/.cache/pip/wheels/13/81/24/2881a16a60296f7d5c598975a7c393cced26fa31c2f039d483
Successfully built u2fval
Installing collected packages: M2Crypto, pyasn1, pyasn1-modules, python-u2flib-server, SQLAlchemy, WebOb, cachetools, u2fval
Successfully installed M2Crypto-0.22.3 SQLAlchemy-1.0.8 WebOb-1.4.1 cachetools-1.1.1 pyasn1-0.1.8 pyasn1-modules-0.0.7 python-u2flib-server-3.2.0 u2fval-0.9.0

(u2fval.with.wheel) $ pip list
cachetools (1.1.1)
M2Crypto (0.22.3)
pip (7.1.2)
pyasn1 (0.1.8)
pyasn1-modules (0.0.7)
python-u2flib-server (3.2.0)
setuptools (18.2)
SQLAlchemy (1.0.8)
u2fval (0.9.0)
WebOb (1.4.1)
wheel (0.24.0)

(u2fval.with.wheel) $ u2fval db init
Database intialized!

**Comment by dainnilsson** [comment]
There was an error in the entry_points (as you spotted) that I've now fixed. Can you test it and see if your issue is resolved? It might also fix the other issue you opened. Since this change isn't in the latest release I'm providing you with a dev build to try out, here: https://drive.google.com/file/d/0B4Zi9B5izoaCZVNHZzdMZWk3ZHM/view?usp=sharing

To install it, download and run "pip install u2fval-0.9.1.dev0.tar.gz"

**Comment by patatetom** [comment]
hi,
will try tonight...
lacsaP

2015-09-15 16:19 GMT+02:00 Dain Nilsson <notifications@github.com>:

**Comment by patatetom** [comment]
yes resolved : installation goes well, with or without wheel.
about /etc/yubico/, a warning message might be welcome when the user does not have sufficient rights... or an other place for configuration files...
