### ISSUE TITLE
« u2fval run » vs « u2fval run --client »

### ISSUE THREAD

**Issue by patatetom** [Yubico/u2fval#9]
the database contains a single record :
```
(u2fval)$ u2fval client list
example
(u2fval)$ u2fval client show example
Client: example
AppID: https://localhost.localdomain
FacetIDs:
  https://localhost.localdomain
```
when I start the server without client setting, it returns nothing when queried :
```
# server side
(u2fval)$ u2fval run
Starting server on http://localhost:8080...
127.0.0.1 - - [18/Sep/2015 09:08:19] "GET /example/register HTTP/1.1" 200 2

# client side
$ curl http://localhost:8080/example/register
[]
```
but when I start the server with client setting, it returns what is expected when queried :
```
# server side
(u2fval)$ u2fval run --client example
Running in single-client mode for client: 'example'
Starting server on http://localhost:8080...
127.0.0.1 - - [18/Sep/2015 09:08:50] "GET /example/register HTTP/1.1" 200 175

# client side
$ curl http://localhost:8080/example/register
{"authenticateRequests": [], "registerRequests": [{"challenge": "C79zjOpVc_UNIi_ujZtbEZr1dsVrD4XN_U1MdeY5UO0", "version": "U2F_V2", "appId": "https://localhost.localdomain"}]}
```

**Comment by dainnilsson** [comment]
When running without --client, you are running in multi-client mode. The URL for the register command should then be of the form:

http://<host>/<client>/<username>/register

You're only specifying:

http://<host>/<client>/register, which is being mapped to:
http://<host>/<client>/<username>, with username=register. As specified in the REST API documentation, a GET request to the user endpoint returns a list of registered device descriptors, an empty list in your case.

**Comment by patatetom** [comment]
ok for the start mode (multi/single) but when started in multi-client, u2fval returns empty responses :
```
(u2fval)$ u2fval client list
test
(u2fval)$ u2fval client show test
Client: test
AppID: https://localhost.localdomain:4443
FacetIDs:
  https://localhost.localdomain:4443
```
I start the server in single client mode :
```
(u2fval)$ u2fval run --client test
Running in single-client mode for client: 'test'
Starting server on http://localhost:8080...
```
and I start a registration :
```
$ curl http://localhost:8080/test/register
{"authenticateRequests": [], "registerRequests": [{"challenge": "GhJ1HCJIeflgCRmGSpypg6OGSKjJwGxz8SzIyUV9jtI", "version": "U2F_V2", "appId": "https://localhost.localdomain:4443"}]}
```
the return is ok and the server side is ok (382 bytes returned):
```
127.0.0.1 - - [23/Sep/2015 09:48:25] "GET /test/register HTTP/1.1" 200 382
```
now, I start the server in multi-client mode :
```
...
KeyboardInterrupt
(u2fval)$ u2fval run
Starting server on http://localhost:8080...
```
and I replay the curl request :
```
$ curl http://localhost:8080/test/register
[]
```
the return is ko (nothing, no challenge, etc...) and the server returns only 2 bytes ([]) :
```
127.0.0.1 - - [23/Sep/2015 09:56:51] "GET /test/register HTTP/1.1" 200 2
```
a request on a bad client returns, as it should be, an error :
```
$ curl http://localhost:8080/bad/register
<html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.<br /><br />
No row was found for one()


 </body>
</html>
```
```
127.0.0.1 - - [23/Sep/2015 09:57:18] "GET /bad/register HTTP/1.1" 500 254
```
sorry for my very broken English

**Comment by dainnilsson** [comment]
Like I explained in the previous comment, the request you're sending that is returning an empty list "[]", is being interpreted as a GET on a user. Your URL:

http://localhost:8080/test/register

is getting registered devices for the _client_ named test, for the _user_ named register. It is the same as: 

http://localhost:8080/test/bob

...which would return a list of registered devices for the _user_ named bob.

 What you're probably looking for is to start a registration, in which case your URL should be:

http://localhost:8080/test/bob/register

I think you're confusing clients with users.

**Comment by patatetom** [comment]
yes, I'm really confusing : the *client* is the application (my bottle web app for example) which requesting u2fval server for registration (or authentication) and the *user* is a user of this application. Is it right ?
and yes I want to start a device registration.

**Comment by dainnilsson** [comment]
That is correct. So, if you have multiple clients (applications) you need to start the path with the client name. After that you add the username of the user in this application, then lastly add _register_ as the command, for example:

http://localhost:8080/mybottleapp/myusername/register

**Comment by patatetom** [comment]
it works much better now ! thank you.
